### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by sborse3** [google/RB-Modulation#10]
Hi @LituRout, thanks for such great work! Please could you let me know if there's any way to publicly access the styles in StyleAligned dataset?

**Comment by LituRout** [comment]
Hi @sborse3, thanks for your kind words! The dataset was curated by the authors of StyleAligned. Some of those images can be found in publicly available repos like https://github.com/google/dreambooth. I do not know any other way to publicly access the styles. You may have to ask the authors of StyleAligned for the dataset.

**Comment by sborse3** [comment]
Thanks!
